analysis:
  active: true
  heuristics: true
  http_default_ports:
  - 80
  indicators_types:
  - all
  iocs: true
  max_ports: 1024
  remote: false
  scoring:
    weights: {}
  tls_default_ports:
  - 443
  - 465
  - 636
  - 989
  - 990
  - 993
  - 995
  - 5223
  whitelist: true
backend:
  login: userlogin
  password: userpassword
  misp_sync_interval_hours: 6
  mvt_sync_interval_hours: 24
  remote_access: true
frontend:
  backend_option: true
  capture_export: server
  download_links: false
  http_port: 8000
  remote_access: true
  shutdown_option: true
  slideshow: true
  sparklines: true
  spyguard_server: https://spyguard.net
  ui_zoom: 100
  update: false
  user_lang: userlang
  virtual_keyboard: true
network:
  in: wlan
  internet_check: https://example.net
  out: lo
  ssids:
  - Free
  - Public
  - Wifi
  - Coffee
  - Netgear
  - Default
  - D-link
  - Guest
  - WLAN
  - ZyXEL
  - Asus
  - Wireless
  tokenized_ssids: true
project:
  path: /usr/share/spyguard
  tags_url: https://api.github.com/repos/SpyGuard/spyguard/tags
